//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJServicios.DB.Interface
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceMovement
    {
        public long Id { get; set; }
        public string City { get; set; }
        public string STFRequirement { get; set; }
        public decimal Amount { get; set; }
        public string Observations { get; set; }
        public string Support { get; set; }
        public long MovementTypeId { get; set; }
        public long EmployeeId { get; set; }
        public long AgentId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual MovementType MovementType { get; set; }
    }
}
